---
gemfile: Gemfile

PreCommit:
  MdLint:
    enabled: true
    description: "Lint Markdown files"
    include:
      - "**/*.md"
  BundleInstall:
    enabled: true
    required: false
    execute: bundle install