title: Normandale Ltd
email: enquiries@normandaleproducts.com
description: ""
baseurl: ""
url: "https://normandaleproducts.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.28.0"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

atom_feed:
  hide: true

include: ["_pages"]

site:
  locale: en-GB
logo: "/assets/images/tiny-logo.png"
masthead_title: " "

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
